baseURL = 'https://davidstclair.github.io'
languageCode = 'en-us'
title = 'David StClair'
theme = "beautifulhugo"

copyright = "© Copyright notice"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10
